In [1]:
import pandas as pd

from src.core import file_manager as fm
from src.embeddings.constants import EMBEDDING_MODELS_TRANSLATION

In [2]:
# df = pd.read_csv(fm.filename_from_data_dir('output/patient/clean_sentences.csv'))


# sentences_to_add_manual_label = df.sample(n=10000, random_state=42)['txt']


# output_file = fm.filename_from_data_dir('output/patient/manual_label/sentences_to_add_label_manual.csv')

# sentences_to_add_manual_label.to_csv(output_file, index=False)

# sentences_to_add_manual_label.head()

8285                                              Quase 39
5090     Meu nariz tá entupido né mas não tá me incomod...
9816          Vou avisar ao meu filho da upa granha Lisboa
23101    Boa noite, Valéria. Desde sexta que estou com ...
11817                              estava espirrando muito
Name: txt, dtype: object

In [3]:
# anottated_path = fm.filename_from_data_dir('output/patient/manual_label/sentences_with_label_manual.csv')

# anottated = pd.read_csv(anottated_path)

# anottated

                                                    txt           intent
0                                              Quase 39           others
1     Meu nariz tá entupido né mas não tá me incomod...  inform_symptoms
2          Vou avisar ao meu filho da upa granha Lisboa           others
3     Boa noite, Valéria. Desde sexta que estou com ...  inform_symptoms
4                               estava espirrando muito  inform_symptoms
...                                                 ...              ...
1995                   E na tv já ouvi falar q não pode           others
1996  E eu estou na casa do meu namorado, o irmão de...           others
1997                           Onde posso fazer o teste   request_inform
1998                      Obrigado pela ajuda e atenção         greeting
1999                              Irritação na garganta  inform_symptoms

[2000 rows x 2 columns]

In [4]:
pd.read_csv(fm.filename_from_data_dir('output/patient/clean_sentences.csv'))

,_id,cri,atu,idp,ori,txt,created_at,id,seq,original_txt
0,7Nmt894SbdLamfwAo-1,2020-05-04T21:15:55.119Z,2020-05-04T21:53:06:605Z,2CNgApLrPbw5bsyxG,patient,Tô muito nervosa Marcela com tudo isso,20-05-04T21:15,7Nmt894SbdLamfwAo,1,Tô muito nervosa Marcela com tudo isso
1,7Nmt894SbdLamfwAo-2,2020-05-04T21:16:21.726Z,2020-05-04T21:53:06:605Z,2CNgApLrPbw5bsyxG,patient,O meu problema é psicológico nem dormi es...,20-05-04T21:16,7Nmt894SbdLamfwAo,2,O meu problema é psicológico nem dormi es...
2,7Nmt894SbdLamfwAo-3,2020-05-04T21:16:49.298Z,2020-05-04T21:53:06:605Z,2CNgApLrPbw5bsyxG,patient,Com muito medo,20-05-04T21:16,7Nmt894SbdLamfwAo,3,Com muito medo
3,7Nmt894SbdLamfwAo-5,2020-05-04T21:17:23.211Z,2020-05-04T21:53:06:605Z,2CNgApLrPbw5bsyxG,patient,Sim,20-05-04T21:17,7Nmt894SbdLamfwAo,5,Sim
4,7Nmt894SbdLamfwAo-6,2020-05-04T21:17:43.786Z,2020-05-04T21:53:06:605Z,2CNgApLrPbw5bsyxG,patient,A 3 meses atrás quando o meu esposo faleceu,20-05-04T21:17,7Nmt894SbdLamfwAo,6,A 3 meses atrás quando o meu esposo faleceu
...,...,...,...,...,...,...,...,...,...,...
26749,Q9eztCPd6c3n8Pqvo-10,2020-05-05T12:10:02.461Z,2020-05-05T12:15:50:697Z,zzb53cgwqLBSWA2Kg,patient,"Ñ, só pressão baixa",20-05-05T12:10,Q9eztCPd6c3n8Pqvo,10,"Ñ, só pressão baixa"
26750,Q9eztCPd6c3n8Pqvo-16,2020-05-05T12:12:45.348Z,2020-05-05T12:15:50:697Z,zzb53cgwqLBSWA2Kg,patient,Atende ?,20-05-05T12:12,Q9eztCPd6c3n8Pqvo,16,Atende ?
26751,Q9eztCPd6c3n8Pqvo-20,2020-05-05T12:14:06.754Z,2020-05-05T12:15:50:697Z,zzb53cgwqLBSWA2Kg,patient,Vou ter q ir na Upa,20-05-05T12:14,Q9eztCPd6c3n8Pqvo,20,Vou ter q ir na Upa
26752,Q9eztCPd6c3n8Pqvo-21,2020-05-05T12:14:17.802Z,2020-05-05T12:15:50:697Z,zzb53cgwqLBSWA2Kg,patient,Por que trabalho em mercantil,20-05-05T12:14,Q9eztCPd6c3n8Pqvo,21,Por que trabalho em mercantil
26753,Q9eztCPd6c3n8Pqvo-27,2020-05-05T12:15:07.564Z,2020-05-05T12:15:50:697Z,zzb53cgwqLBSWA2Kg,patient,É na varjota q trabalho,20-05-05T12:15,Q9eztCPd6c3n8Pqvo,27,É na varjota q trabalho

In [5]:
def read_annotated_sentences(embedding_name, actor='patient', variation='without_others_intent/k100_without_sentences_higher_than_median'):
    file_name = fm.filename_from_data_dir(
        f'output/{actor}/{variation}/{embedding_name}/annotated_sentences.csv'
    )

    return pd.read_csv(file_name)

In [6]:
df_bert = read_annotated_sentences('bert_pt')

df_bert.describe()

,txt,annotated_txt,intent
count,8837,8837,8837
unique,8837,8837,4
top,Tô muito nervosa Marcela com tudo isso,Tô muito nervosa Marcela com tudo isso,inform_symptoms
freq,1,1,5495

In [7]:
df_glove =  read_annotated_sentences('glove')

df_glove.describe()

                   txt   annotated_txt           intent
count             8900            8900             8900
unique            8900            8900                4
top     Com muito medo  Com muito medo  inform_symptoms
freq                 1               1             7120

In [8]:
df_flair = read_annotated_sentences('flair_pt')

df_flair.describe()

,txt,annotated_txt,intent
count,8840,8840,8840
unique,8840,8840,4
top,Tô muito nervosa Marcela com tudo isso,Tô muito nervosa Marcela com tudo isso,inform_symptoms
freq,1,1,6229

In [9]:
df_lasbe = read_annotated_sentences('lasbe')

df_lasbe.describe()

,txt,annotated_txt,intent
count,8007,8007,8007
unique,8007,8007,4
top,Tô muito nervosa Marcela com tudo isso,Tô muito nervosa Marcela com tudo isso,inform_symptoms
freq,1,1,4682

In [10]:
df_use = read_annotated_sentences('use')

df_use.describe()

,txt,annotated_txt,intent
count,6928,6928,6928
unique,6928,6928,4
top,Tem algum remédio que a pessoa tome para se a...,Tem algum remédio que a pessoa tome para se a...,inform_symptoms
freq,1,1,4115

In [11]:
# pd.merge(df_bert['txt'], df_glove['txt'], how ='inner', on ='txt')

dfs = [df_bert, df_flair, df_glove, df_lasbe, df_use]

# pd.concat(dfs, axis=1, join='inner')


df_merged = dfs[0]
for df in dfs[1:]:       
    df_merged = pd.merge(df_merged['txt'], df['txt'], on='txt', how='inner')

df_merged

                                                    txt
0                                             Tá  certo
1                                               Tá  bom
2                                            Boa tarde!
3                                             Obrigada!
4                                             Obrigado!
...                                                 ...
1062  Muita muita dor de cabeça tossindo muito uma t...
1063  Leve falta de ar a respiração está ficando um ...
1064  Estou com desconforto no peito, com nariz, gua...
1065  Hoje eu senti uma leve febre e uma leve dor de...
1066  Estou com febre , dor de cabeça molesa no corp...

[1067 rows x 1 columns]

In [10]:
def get_path_df(embedding_name, type='train'):
    return fm.filename_from_data_dir(
        f'output/neural_models/patient/{embedding_name}/data_{type}.csv'
        )

In [11]:
df_trains = [
  pd.read_csv(get_path_df(embedding_name=embedding_name, type='train'))
  for embedding_name in EMBEDDING_MODELS_TRANSLATION.keys()
]

In [4]:
df_train_merged = pd.concat(df_trains, ignore_index=True)

df_train_merged = df_train_merged.drop_duplicates(subset=['correct_txt'])

df_train_merged

,txt,annotated_txt,intent,correct_txt,tokens
0,Não era só isso mesmo,Não era só isso mesmo,greeting,Não era só isso mesmo,NaN
1,Síndrome Arnold Chiari com invaginacao basilar...,Síndrome Arnold Chiari com invaginacao basilar...,inform_symptoms,Síndrome Arnold Chiari com invaginacao basilar...,NaN
2,Desde ontem estou com febre e dor de cabeça e ...,Desde ontem estou com [febre](SINTOMA) e [dor ...,inform_symptoms,Desde ontem estou com febre e dor de cabeça e ...,NaN
3,"Não, estou","Não, estou",greeting,"Não, estou",NaN
4,Falta de ar normal porque tenho asma,[Falta de ar](SINTOMA) normal porque tenho [as...,inform_symptoms,Falta de ar normal porque tenho asma,NaN
...,...,...,...,...,...
29033,A dor de garganta na semana passada,A [dor de garganta](SINTOMA) na semana passada,inform_symptoms,A dor de garganta na semana passada,NaN
29034,Pode deixa eu vou colocar,Pode deixa eu vou colocar,request_inform,Pode deixa eu vou colocar,NaN
29041,"Estou em casa, não tenho dinheiro pra ir no po...","Estou em casa, não tenho dinheiro pra ir no po...",request_inform,"Estou em casa, não tenho dinheiro pra ir no po...",NaN
29050,A senhora acha que não é covid,A senhora acha que não é covid,request_inform,A senhora acha que não é covid,NaN
29053,Como devo proceder nessa situação?,Como devo proceder nessa situação?,request_inform,Como devo proceder nessa situação?,NaN

In [5]:
df_train_merged['intent'].value_counts()

inform_symptoms    10797
request_inform      2195
greeting            1815
inform_medicine     1384
Name: intent, dtype: int64

In [12]:
df_tests = [
  pd.read_csv(get_path_df(embedding_name=embedding_name, type='test'))
  for embedding_name in EMBEDDING_MODELS_TRANSLATION.keys()
]

df_test_merged = pd.concat(df_tests, ignore_index=True)

df_test_merged = df_test_merged.drop_duplicates(subset=['correct_txt'])

df_test_merged

,txt,annotated_txt,intent,correct_txt,tokens
0,Não. Já esclareceu tudo. Obrigado pela ajuda.,Não. Já esclareceu tudo. Obrigado pela ajuda.,greeting,Não. Já esclareceu tudo. Obrigado pela ajuda.,NaN
1,"Okay então, obrigado.","Okay então, obrigado.",greeting,"Okay então, obrigado.",NaN
2,Dipirona e loratadina,Dipirona e loratadina,inform_medicine,Dipirona e loratadina,NaN
3,Isso estou com tosse e muita moleza no corpo,Isso estou com [tosse](SINTOMA) e muita moleza...,inform_symptoms,Isso estou com tosse e muita moleza no corpo,NaN
4,estou com alguns sintomas da covid 19.,estou com alguns sintomas da covid 19.,inform_symptoms,estou com alguns sintomas da covid 19.,NaN
...,...,...,...,...,...
12441,Perdi* o olfato e o paladar,Perdi* o olfato e o paladar,inform_symptoms,Perdi* o olfato e o paladar,NaN
12446,Enquanto isso é pra tomar algum medicamento,Enquanto isso é pra tomar algum medicamento,inform_medicine,Enquanto isso é pra tomar algum medicamento,NaN
12449,Dexmine,Dexmine,inform_medicine,Dexmine,NaN
12452,Tomo velija 60mg,Tomo velija 60mg,inform_medicine,Tomo velija 60mg,NaN
12455,Renite conta?,Renite conta?,request_inform,Renite conta?,NaN

In [14]:
df_test_merged['intent'].value_counts()

inform_symptoms    6386
request_inform     1263
greeting           1107
inform_medicine     826
Name: intent, dtype: int64

In [19]:
used_data = pd.concat([df_train_merged, df_test_merged], ignore_index=True).drop_duplicates(subset=['correct_txt'])

In [18]:
annotated_sentences = pd.read_csv(fm.filename_from_data_dir('output/patient/annotated_sentences.csv'))

annotated_sentences

,txt,annotated_txt
0,Tô muito nervosa Marcela com tudo isso,Tô muito nervosa Marcela com tudo isso
1,O meu problema é psicológico nem dormi es...,O meu problema é psicológico nem dormi es...
2,Com muito medo,Com muito medo
3,Sim,Sim
4,A 3 meses atrás quando o meu esposo faleceu,A 3 meses atrás quando o meu esposo faleceu
...,...,...
26749,"Ñ, só pressão baixa","Ñ, só pressão baixa"
26750,Atende ?,Atende ?
26751,Vou ter q ir na Upa,Vou ter q ir na Upa
26752,Por que trabalho em mercantil,Por que trabalho em mercantil
26753,É na varjota q trabalho,É na varjota q trabalho

In [7]:
untrained_sentences = annotated_sentences[
  ~annotated_sentences['txt'].isin(df_train_merged['correct_txt'])
  ]

In [20]:
not_used_sentences = annotated_sentences[
  ~annotated_sentences['txt'].isin(used_data['correct_txt'])
  ]

In [21]:
not_used_sentences.describe()

         txt annotated_txt
count   7926          7926
unique  7926          7926
top      Sim           Sim
freq       1             1

In [22]:
sentences_to_add_manual_label = not_used_sentences.sample(n=1000, random_state=42)['txt']

output_file = fm.filename_from_data_dir('output/patient/manual_label/not_used_sentences_to_add_label_manual.csv')

sentences_to_add_manual_label.to_csv(output_file, index=False)

sentences_to_add_manual_label.head()

17156                                              Foi sim
1024                                        Vou Fazer Isso
15060    Na verdade tô falando como se fosse minha mãe ...
4481                       Ontem tive picos de 35,3 a 36,9
8507            Se eu precisar amanhã volto a procurar vcs
Name: txt, dtype: object

In [8]:
sentences_to_add_manual_label = untrained_sentences.sample(n=400, random_state=42)['txt']

output_file = fm.filename_from_data_dir('output/patient/manual_label/untrained_sentences_to_add_label_manual.csv')

sentences_to_add_manual_label.to_csv(output_file, index=False)

sentences_to_add_manual_label.head()

8510                               Desculpa qualquer coisa
13774                         Sim,Dipirona 1g e vitamina c
11928    Ate hoje nao sinto cheiro de nada ... Por msis...
4031     Aqui se eu tiver contaminada é só as pessoas q...
25702    Meu nome é Regina Nascimento Mesquita tenho 57...
Name: txt, dtype: object

In [29]:
input_file = fm.filename_from_data_dir('output/patient/manual_label/untrained_sentences_with_label_manual.csv')

df_tmp =  pd.read_csv(input_file)

df_tmp['intent'].value_counts()

others             273
inform_symptoms     68
request_inform      27
inform_medicine     17
greeting            15
Name: intent, dtype: int64

In [38]:
file = fm.filename_from_data_dir('output/patient/manual_label/not_used_sentences_with_label_manual.csv')

not_seen = pd.read_csv(file)

not_seen[not_seen.txt.isin(df_tmp.txt)].count()

txt       34
intent    34
dtype: int64

In [40]:
not_seen.intent.value_counts()

others             788
inform_symptoms    102
request_inform      47
inform_medicine     33
greeting            30
Name: intent, dtype: int64

In [44]:
not_seen_without_others = not_seen[not_seen.intent != 'others']

not_seen_without_others.intent.value_counts()

inform_symptoms    102
request_inform      47
inform_medicine     33
greeting            30
Name: intent, dtype: int64

In [53]:
for intent in not_seen_without_others.intent.unique():
  print(not_seen_without_others[not_seen_without_others['intent'] ==  intent][:25].count())

txt       25
intent    25
dtype: int64
txt       25
intent    25
dtype: int64
txt       25
intent    25
dtype: int64
txt       25
intent    25
dtype: int64